import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ExternalLink, Note, PageHeading, useLearningWorkspace } from '../components/learning/Workspace';
import { SpeechPractice, VoiceRecorder } from '../components/learning/SpeechPractice';
import { RESEARCH_DATE } from '../data/learning-hub';

const sources = {
  sat: 'https://satsuite.collegeboard.org/sat/whats-on-the-test/structure',
  act: 'https://www.act.org/content/act/en/products-and-services/the-act-educator/the-act-test/enhancements-k12/faqs.html',
  toefl: 'https://www.ets.org/content/ets-org/language-master/in/home/toefl/institutions/ibt/about/content-structure.html',
};
function FormatTable({ rows }: { rows: string[][] }) {
  return <div className="learn-table-wrap"><table className="learn-table"><thead><tr><th>Seção</th><th>Questões / itens</th><th>Tempo</th></tr></thead><tbody>{rows.map(row => <tr key={row[0]}>{row.map((cell, index) => index === 0 ? <th key={cell} scope="row">{cell}</th> : <td key={index}>{cell}</td>)}</tr>)}</tbody></table></div>;
}
function ExamFooter({ exam }: { exam: keyof typeof sources }) {
  return <p className="learn-source">Formato conferido em {RESEARCH_DATE}. <ExternalLink href={sources[exam]} className="learn-text-link">Consultar a fonte oficial</ExternalLink>. Os exercícios ARTX são autorais e não produzem uma nota oficial. Antes de escolher uma prova, confira a exigência do curso e da instituição.</p>;
}
export function SatTrack() {
  return <div className="learn-page"><PageHeading eyebrow="PREPARAÇÃO ACADÊMICA · SAT" title="Seu espaço para o SAT continua aqui." text="O SAT avalia leitura, escrita e matemática. Use esta trilha quando quiser praticar a prova, mantendo o inglês básico na sua rotina principal." />
    <div className="learn-exam-hero sky"><div><span className="learn-eyebrow">DIGITAL SAT</span><h2>Leia com atenção.<br />Resolva com método.</h2><p>Dois módulos por seção; o segundo se adapta ao resultado do primeiro. São 2h14 de prova e uma pausa de 10 minutos entre as seções.</p></div><strong aria-hidden="true">SAT<span>READ · REASON · SOLVE</span></strong></div>
    <div className="learn-actions"><Link className="learn-button primary" to="/simulados">Abrir simulados ARTX →</Link><Link className="learn-button" to="/sat/resultados">Meu painel SAT</Link><Link className="learn-button" to="/historico">Histórico de tentativas</Link><Link className="learn-button" to="/guia">Guia do SAT</Link></div>
    <div className="learn-columns"><section className="learn-card"><h2>Como a prova se organiza</h2><FormatTable rows={[[ 'Reading and Writing', '54', '64 min (2 × 32)' ], [ 'Math', '44', '70 min (2 × 35)' ]]} /><p>Use o Bluebook para experimentar o aplicativo e os testes oficiais. Os simulados daqui são prática complementar.</p></section><section className="learn-card"><h2>Prática oficial gratuita</h2><p>Comece sem cronômetro para entender os erros. Depois pratique um módulo com tempo.</p><ExternalLink href="https://satsuite.collegeboard.org/practice/practice-tests/bluebook" className="learn-button primary">Testes oficiais no Bluebook</ExternalLink><ol className="learn-instructions"><li>Escolha uma habilidade por sessão.</li><li>Justifique por que a resposta está certa e as outras não.</li><li>Refaça os erros alguns dias depois, sem consultar a solução.</li></ol></section></div><section className="learn-card"><Note id="sat-notes" title="Meu caderno SAT" placeholder="Teste e questão · por que errei · regra ou estratégia · o que revisar…" /></section><ExamFooter exam="sat" /></div>;
}
const actQuestions = [
  { text: 'Choose the correct sentence.', options: ['The list of topics is on the desk.', 'The list of topics are on the desk.', 'The list of topics be on the desk.'], answer: 0, why: 'O núcleo do sujeito é list, singular. “Of topics” não transforma o sujeito em plural; use is.' },
  { text: 'The team collected more data. However, its conclusion remained uncertain. What does “However” signal?', options: ['A result', 'A contrast', 'An example'], answer: 1, why: 'Mesmo com mais dados, a conclusão continuou incerta. However introduz contraste, não causa.' },
  { text: 'A student reads 18 pages in 30 minutes at a constant rate. How many pages in 50 minutes?', options: ['24', '36', '30'], answer: 2, why: 'A taxa é 18 ÷ 30 = 0,6 página/min. Em 50 minutos: 0,6 × 50 = 30 páginas.' },
];
function ActWarmup() {
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [checked, setChecked] = useState(false);
  return <form className="learn-card learn-quiz" onSubmit={e => { e.preventDefault(); setChecked(true); }}><span className="learn-eyebrow">AQUECIMENTO AUTORAL · SEM CRONÔMETRO</span><h2>Três formas de raciocinar</h2><p>Pratique concordância, conexão entre ideias e proporção. Isto não é um simulado completo do ACT.</p>{actQuestions.map((q, i) => <fieldset key={q.text}><legend lang="en">{q.text}</legend>{q.options.map((option, j) => <label className="learn-choice" key={option}><input name={`act-${i}`} type="radio" required disabled={checked} checked={answers[i] === j} onChange={() => setAnswers(a => ({ ...a, [i]: j }))} /><span lang="en">{option}</span></label>)}{checked && <p className={answers[i] === q.answer ? 'learn-correct' : 'learn-feedback'}>{answers[i] === q.answer ? 'Correto. ' : `Resposta: ${q.options[q.answer]} `}{q.why}</p>}</fieldset>)}{checked ? <button className="learn-button" type="button" onClick={() => { setChecked(false); setAnswers({}); }}>Tentar novamente</button> : <button className="learn-button primary">Conferir e entender</button>}</form>;
}
export function ActTrack() {
  return <div className="learn-page"><PageHeading eyebrow="PREPARAÇÃO ACADÊMICA · ACT" title="Conheça o ACT, no formato atual." text="O ACT é uma prova acadêmica com inglês, matemática e leitura. Não substitui uma prova de proficiência em inglês." /><div className="learn-exam-hero peach"><div><span className="learn-eyebrow">ENHANCED ACT</span><h2>Compreensão.<br />Clareza. Raciocínio.</h2><p>O composto considera English, Math e Reading. Science e Writing são opcionais; confirme o que a instituição exige.</p></div><strong aria-hidden="true">ACT<span>ENGLISH · MATH · READING</span></strong></div>
    <div className="learn-columns"><section className="learn-card"><h2>Formato atualizado</h2><FormatTable rows={[[ 'English', '50', '35 min' ], [ 'Math', '45', '50 min' ], [ 'Reading', '36', '40 min' ], [ 'Science (opcional)', '40', '40 min' ]]} /><p>As três seções principais somam 2h05, sem pausas. A escala continua de 1 a 36.</p><ExternalLink href="https://global.act.org/content/global/en/products-and-services/the-act-non-us/test-preparation/test-enhancements.html" className="learn-text-link">Atualizações para candidatos internacionais</ExternalLink></section><section className="learn-card"><h2>Comece com material oficial</h2><p>Testes gratuitos por seção, com e sem tempo, versões para imprimir e gabaritos. Escolha um teste do formato atualizado.</p><ExternalLink href="https://www.act.org/content/act/en/products-and-services/the-act/test-preparation/free-act-test-prep.html" className="learn-button primary">Abrir prática gratuita do ACT</ExternalLink><ol className="learn-instructions"><li>Comece por English ou Reading, sem tempo.</li><li>Identifique a regra ou a evidência para cada resposta.</li><li>Registre o erro e volte a ele em outra sessão.</li></ol></section></div><ActWarmup /><section className="learn-card"><Note id="act-notes" title="Meu caderno ACT" /></section><ExamFooter exam="act" /></div>;
}
function SentenceBuilder() {
  const chunks = ['the lesson starts?', 'Could you', 'what time', 'tell me'];
  const [order, setOrder] = useState<number[]>([]);
  const [checked, setChecked] = useState(false);
  const correct = order.join(',') === '1,3,2,0';
  return <div className="learn-sentence"><h3>Build a Sentence · organizar uma pergunta</h3><p>Toque nos trechos na ordem correta. Em uma pergunta indireta, observe a posição do sujeito e do verbo.</p><div className="learn-actions">{chunks.map((word, index) => <button className="learn-button" key={word} disabled={order.includes(index) || checked} onClick={() => setOrder(o => [...o, index])}>{word}</button>)}</div><p className="learn-sentence-answer" lang="en">{order.length ? order.map(i => chunks[i]).join(' ') : 'Sua frase aparece aqui…'}</p><div className="learn-actions"><button className="learn-button primary" disabled={order.length !== chunks.length} onClick={() => setChecked(true)}>Conferir frase</button><button className="learn-button" onClick={() => { setOrder([]); setChecked(false); }}>Recomeçar</button></div>{checked && <p className={correct ? 'learn-correct' : 'learn-feedback'}>{correct ? 'Isso mesmo! ' : 'A ordem é: Could you tell me what time the lesson starts? '}Depois de “Could you tell me”, use a ordem afirmativa: the lesson starts.</p>}</div>;
}
export function ToeflTrack() {
  const { state } = useLearningWorkspace();
  const [section, setSection] = useState('Writing');
  return <div className="learn-page"><PageHeading eyebrow="PROFICIÊNCIA · TOEFL iBT" title="Inglês para entender e participar." text="TOEFL é o nome da prova de proficiência. O formato mudou em 21 de janeiro de 2026; esta aba usa a estrutura atual." /><div className="learn-exam-hero lavender"><div><span className="learn-eyebrow">TOEFL iBT · 2026</span><h2>Quatro habilidades.<br />Um inglês conectado.</h2><p>Reading e Listening adaptativos. A escala atual vai de 1 a 6, em meios pontos; há uma nota geral comparável de 0–120 durante a transição de dois anos.</p></div><strong aria-hidden="true">TOEFL<span>READ · LISTEN · WRITE · SPEAK</span></strong></div>
    <div className="learn-columns"><section className="learn-card"><h2>Estrutura e tempos-base</h2><FormatTable rows={[[ 'Reading', '50', 'aprox. 30 min' ], [ 'Listening', '47', 'aprox. 29 min' ], [ 'Writing', '12', 'aprox. 23 min' ], [ 'Speaking', '11', 'aprox. 8 min' ]]} /><p>Tempos e itens podem variar com a adaptação. Reserve aproximadamente 2 horas, incluindo instruções.</p></section><section className="learn-card"><h2>Material oficial e seu ponto de partida</h2><p>Seu nível de prática está em {state.settings.level}. Use estas tarefas para conhecer a prova e continue fortalecendo a base no plano de inglês.</p><ExternalLink href="https://www.ets.org/toefl/test-takers/ibt/prepare.html" className="learn-button primary">Preparação oficial ETS</ExternalLink><p>Procure as amostras gratuitas atualizadas para 2026. A página também oferece produtos pagos.</p><Link className="learn-text-link" to="/praticar">Praticar a base primeiro →</Link></section></div>
    <section className="learn-card"><span className="learn-eyebrow">LABORATÓRIO AUTORAL · NÃO É UMA PROVA OFICIAL</span><h2>Experimente uma habilidade</h2><div className="learn-filter" role="group" aria-label="Habilidade TOEFL">{['Reading', 'Listening', 'Writing', 'Speaking'].map(s => <button key={s} className={section === s ? 'selected' : ''} aria-pressed={section === s} onClick={() => setSection(s)}>{s}</button>)}</div>
    {section === 'Reading' && <div><h3>Read in Daily Life · um aviso</h3><blockquote lang="en">The library’s second floor will close at 4 p.m. on Friday for maintenance. Books can still be returned at the ground-floor desk until 6 p.m. Online renewals remain available.</blockquote><p>Você chega às 17h de sexta. Como pode devolver seu livro?</p><details><summary>Conferir a explicação</summary><p>No balcão do térreo, aberto até 18h. A restrição das 16h se aplica ao segundo andar, não ao serviço de devolução.</p></details><p>Na prova atual, a seção também trabalha completar palavras e textos acadêmicos.</p></div>}
    {section === 'Listening' && <div><h3>Listen and Choose a Response · pedir ajuda</h3><SpeechPractice text="Would you mind showing me how to renew this book online?" /><p>Qual resposta resolve o pedido?</p><details><summary>A. Yes, I read it last week.</summary><p>Isso fala de uma leitura passada; não oferece a ajuda solicitada.</p></details><details><summary>B. Of course. First, sign in to your library account.</summary><p>Correto: a pessoa aceita ajudar e começa a explicar o procedimento.</p></details><details><summary>C. The book is very interesting.</summary><p>Isso é uma opinião sobre o livro, não uma resposta ao pedido.</p></details><p>Outras tarefas usam conversas, anúncios e falas acadêmicas.</p></div>}
    {section === 'Writing' && <div><SentenceBuilder /><h3>Write an Email · um pedido claro</h3><p>Você perdeu uma aula porque estava doente. Escreva ao professor: explique o motivo, pergunte qual material revisar e proponha como recuperar a atividade. Tente em 7 minutos para praticar; este é um tempo sugerido, não uma regra oficial.</p><Note id="toefl-email" title="Meu e-mail em inglês" placeholder="Hello…" /><details><summary>Revisar meu e-mail</summary><p>Incluí saudação, motivo, pedido e encerramento? O leitor sabe o que preciso? Verifique os verbos e evite traduzir expressões palavra por palavra.</p></details><h3>Academic Discussion · sua contribuição</h3><p>Um professor pergunta: “Should students study alone or in groups?” Escreva uma opinião com uma razão e um exemplo. Reconheça também uma vantagem da outra opção.</p><Note id="toefl-discussion" title="Minha contribuição" /></div>}
    {section === 'Speaking' && <div><h3>Listen and Repeat · escutar e repetir</h3><p>Ouça a frase e repita. Compare palavras omitidas e clareza. Depois tente com o texto fechado.</p><SpeechPractice text="The study room is available after lunch." /><h3>Take an Interview · responder com suas ideias</h3><p lang="en">What is one skill you would like to learn, and why?</p><p>Dê uma resposta direta, explique o motivo e acrescente um exemplo. Use a gravação para se ouvir; não há pontuação automática.</p><VoiceRecorder /><Link className="learn-button" to="/conversacao">Continuar a conversa com um contexto pronto →</Link></div>}
    </section><section className="learn-card"><Note id="toefl-notes" title="Meu caderno TOEFL" /></section><ExamFooter exam="toefl" /></div>;
}
